/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SarbatoriRouteImport } from './routes/sarbatori'
import { Route as AngajatiRouteImport } from './routes/angajati'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnLunaRouteImport } from './routes/$an.$luna'
import { Route as AnLunaPrintPrintSlugRouteImport } from './routes/$an.$luna_.print.$printSlug'

const SarbatoriRoute = SarbatoriRouteImport.update({
  id: '/sarbatori',
  path: '/sarbatori',
  getParentRoute: () => rootRouteImport,
} as any)
const AngajatiRoute = AngajatiRouteImport.update({
  id: '/angajati',
  path: '/angajati',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnLunaRoute = AnLunaRouteImport.update({
  id: '/$an/$luna',
  path: '/$an/$luna',
  getParentRoute: () => rootRouteImport,
} as any)
const AnLunaPrintPrintSlugRoute = AnLunaPrintPrintSlugRouteImport.update({
  id: '/$an/$luna_/print/$printSlug',
  path: '/$an/$luna/print/$printSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angajati': typeof AngajatiRoute
  '/sarbatori': typeof SarbatoriRoute
  '/$an/$luna': typeof AnLunaRoute
  '/$an/$luna/print/$printSlug': typeof AnLunaPrintPrintSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angajati': typeof AngajatiRoute
  '/sarbatori': typeof SarbatoriRoute
  '/$an/$luna': typeof AnLunaRoute
  '/$an/$luna/print/$printSlug': typeof AnLunaPrintPrintSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angajati': typeof AngajatiRoute
  '/sarbatori': typeof SarbatoriRoute
  '/$an/$luna': typeof AnLunaRoute
  '/$an/$luna_/print/$printSlug': typeof AnLunaPrintPrintSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angajati'
    | '/sarbatori'
    | '/$an/$luna'
    | '/$an/$luna/print/$printSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angajati'
    | '/sarbatori'
    | '/$an/$luna'
    | '/$an/$luna/print/$printSlug'
  id:
    | '__root__'
    | '/'
    | '/angajati'
    | '/sarbatori'
    | '/$an/$luna'
    | '/$an/$luna_/print/$printSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngajatiRoute: typeof AngajatiRoute
  SarbatoriRoute: typeof SarbatoriRoute
  AnLunaRoute: typeof AnLunaRoute
  AnLunaPrintPrintSlugRoute: typeof AnLunaPrintPrintSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sarbatori': {
      id: '/sarbatori'
      path: '/sarbatori'
      fullPath: '/sarbatori'
      preLoaderRoute: typeof SarbatoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angajati': {
      id: '/angajati'
      path: '/angajati'
      fullPath: '/angajati'
      preLoaderRoute: typeof AngajatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$an/$luna': {
      id: '/$an/$luna'
      path: '/$an/$luna'
      fullPath: '/$an/$luna'
      preLoaderRoute: typeof AnLunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$an/$luna_/print/$printSlug': {
      id: '/$an/$luna_/print/$printSlug'
      path: '/$an/$luna/print/$printSlug'
      fullPath: '/$an/$luna/print/$printSlug'
      preLoaderRoute: typeof AnLunaPrintPrintSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngajatiRoute: AngajatiRoute,
  SarbatoriRoute: SarbatoriRoute,
  AnLunaRoute: AnLunaRoute,
  AnLunaPrintPrintSlugRoute: AnLunaPrintPrintSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
